# Generated by Django 6.0.2 on 2026-02-11 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('cv', models.UUIDField(unique=True)),
                ('skills', models.TextField(null=True)),
                ('total_exp', models.IntegerField(null=True)),
                ('ollama', models.JSONField(default=None, null=True)),
                ('ollama_gen_time', models.DateTimeField(default=None, null=True)),
                ('openai', models.JSONField(default=None, null=True)),
                ('openai_gen_time', models.DateTimeField(default=None, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cv_candidates',
                'indexes': [models.Index(fields=['email'], name='cv_candidates_idx_1'), models.Index(fields=['skills'], name='cv_candidates_idx_2')],
            },
        ),
    ]
