# Generated by Django 6.0.2 on 2026-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_candidates_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='ext',
            field=models.CharField(max_length=5),
        ),
    ]
