# Generated by Django 6.0.2 on 2026-02-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_candidates_ext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='cv',
            new_name='cv_fileid',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='ext',
        ),
        migrations.AddField(
            model_name='candidates',
            name='cv_filename',
            field=models.CharField(default='resume_unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddConstraint(
            model_name='candidates',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_email_when_not_null'),
        ),
    ]
