# Generated by Django 6.0.2 on 2026-02-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_rename_cv_candidates_cv_fileid_remove_candidates_ext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='cv_filename',
            field=models.CharField(max_length=30),
        ),
    ]
