# Generated by Django 6.0.2 on 2026-02-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_candidates_cv_filename'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidates',
            name='cv_candidates_idx_2',
        ),
        migrations.RenameIndex(
            model_name='candidates',
            new_name='cv_candidates_idx_email',
            old_name='cv_candidates_idx_1',
        ),
        migrations.AlterField(
            model_name='candidates',
            name='cv_fileid',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='cv_filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='ollama',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='ollama_gen_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='openai',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='openai_gen_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='total_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
