# Generated by Django 6.0.2 on 2026-02-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_remove_candidates_cv_candidates_idx_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='cv_fileid',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
