# Generated by Django 6.0.2 on 2026-02-13 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_candidates_cv_fileid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidates',
            name='unique_email_when_not_null',
        ),
    ]
